collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.3261649
color:
  saturation: 0.7315302980132401
  brandStrength: 0.6372547422070056
  rhythmicContrast: 0.591800813563168
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
  lightness: 0.9350368406157941
layout_spectrum: 0.4157706
name: Chance Shelton
